# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.box = "ubuntu/vivid64"
  config.vm.box = "boxcutter/ubuntu1504"

  config.vm.provision :shell, inline: "sudo apt-get install -y git"
  config.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
  config.vm.provision :shell, path: "install-ruby.sh", args: "2.2.3 specific_install", privileged: false
end
